apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: demo
spec:
  replicas: 2
  revisionHistoryLimit: 5 # cuántas versiones guarda para rollback
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # nunca bajar capacidad durante el deploy
      maxSurge: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web # <- este nombre lo usa "kubectl set image"
          image: 386783748837.dkr.ecr.us-east-2.amazonaws.com/nova-demo-app:v1
          ports:
            - containerPort: 3000

          readinessProbe: # ¿puede recibir tráfico?
            httpGet: { path: /healthz, port: 3000 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe: # ¿está vivo o hay que reiniciarlo?
            httpGet: { path: /healthz, port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { memory: 256Mi }
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop: ["ALL"]
